name: deploy-py-lambda
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::794553525198:role/github-actions
          aws-region: us-east-
      - name: build and deploy
        run: |
          chmod +x ./.github/scripts/buildAndDeploy.sh 
          ./.github/scripts/buildAndDeploy.sh
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          LAMBDA_NAME: 'song-of-day-discord-bot'
          AWS_REGION: 'us-east-1'